hashicorp/action-setup-bob

- .gitignore
- action.yml
- bob.js
- dist/index.js
- package-lock.json
- package.json
Set default version of bob to install as latest, 0.0.22
> Update bob to 0.0.22

- README.md
These are instructions/note how to update the bob version in this repo and pushing a new tag.
> add important note

- action.yml
- bob.js
- dist/index.js
> bump bob version

- action.yml
- bob.js
- dist/index.js
Need to wait for https://github.com/hashicorp/bob/actions/runs/3094171318/jobs/5007280994 to finish successfully
> Bump default version of bob to v0.0.30

- action.yml
- bob.js
- dist/index.js
https://github.com/hashicorp/bob/releases/tag/v0.0.31
> Update default version of bob to 0.0.31

- action.yml
- bob.js
- dist/index.js
https://github.com/hashicorp/bob/releases/tag/v0.0.33
> Update default version of bob to 0.0.33

- action.yml
- bob.js
- dist/index.js
Merge after bob 0.0.35 has been cut.
> Bump bob 0.0.35

- dist/index.js
- dist/licenses.txt
- package-lock.json
Signed-off-by: Jaymala Sinha <jaymala@hashicorp.com>
> Update for security fixes

- action.yml
- bob.js
- dist/index.js
Update bob version to point to `v0.0.38`
> Update bob version

- action.yml
- bob.js
- dist/index.js
Will require hashicorp/crt-workflows-common#281 to function.
> Revving to 0.1.4

- action.yml
- bob.js
- dist/index.js
Reverts hashicorp/action-setup-bob#28
> Revert "Revving to 0.1.4"

- action.yml
- bob.js
- dist/index.js
Reverts hashicorp/action-setup-bob#29
> Revert "Revert "Revving to 0.1.4""

- action.yml
- bob.js
- dist/index.js
Released a new version of bob (0.1.9)
> bump to 0.1.9

- dist/index.js
- package-lock.json
- package.json
Update @actions/core to 1.10.0.
Fixes RELENG-294
> Fix GHA deprecations

- .github/dependabot.yml
- .github/workflows/ci.yml
- CODEOWNERS
- META.d/_summary.yaml
- META.d/data.yaml
- META.d/links.yaml
- README.md
- bob.test.js
Adds the following:
* Default CODEOWNERS
* META.d
* (OOB) Branch protection rules on `release/*`
Related:
* Badges
* Enables a basic test CI workflow
Related RELENG-639
> Add Hemidall metadata

- action.yml
- bob.js
- dist/index.js
Upgrade `bob`:
- Point to `bob` version `0.1.11`
- Retagging `action-setup-bob` to `1.0.17`
> Updgrade bob version v1.0.17

- action.yml
- bob.js
- dist/index.js
Upgrade to `0.1.12` bob version
> Upgrade to 0.1.12

- action.yml
- bob.js
- dist/index.js
> update bob version to 0.2.0

- dist/index.js
Missed a step in the release process. Ran `npm run prepare` to add these changes
> npm run prepare

- .github/workflows/ci.yml
- action.yml
https://hashicorp.atlassian.net/browse/SMRE-177?atlOrigin=eyJpIjoiZDZlODI0OGI5ODQ2NGQ0MmEzMTY3MDM0ZDc1ZjFjNzMiLCJwIjoiaiJ9
https://docs.google.com/document/d/1kwq2o70u_WNn-SHxL0zPB94ImMMGHiaEXitMczdx7uQ/edit
> SMRE-177 update to Node20

- action.yml
https://github.com/hashicorp/bob/releases/tag/v0.2.1
> bump bob version to 0.2.1

- bob.js
- dist/index.js
- yarn.lock
update bob version in bob.js and index.js
npm run install
npm run prepare
> fix last commit - the bob version should be updated in 2 other places

- .github/workflows/ci.yml
- action.yml
This also obviates #77 (which fails it's CI tests, I have no idea why).
> TSCCR update
